# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import galeniads.models


class Migration(migrations.Migration):

    dependencies = [
        ('galeniads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='src',
            field=models.FileField(upload_to=galeniads.models.get_upload_path_folder_file),
        ),
        migrations.AlterField(
            model_name='folder',
            name='file_template',
            field=models.FileField(upload_to=galeniads.models.get_upload_path_folder_template),
        ),
    ]
